### ISSUE TITLE
Working with agda-mode

### ISSUE THREAD

**Issue by leokaplan** [banacorn/docker-agda#1]
Hi, I recently downloaded this image and tried to make it work with agda-mode on atom as described on the README. 
The current preferences of the mode are different from the image, for example putting the `docker run ... ` would give me an error as I was running `docker -V`. 
So I tried to give the mode some agda executable to run. I created at `/bin` the following file
```
#!/bin/bash
docker run -i --rm -v /home/mypath:/home/mypath banacorn/agda agda
```
And it almost worked. The connection script has a 1 second timeout. I then changed the value from 1 to 10 seconds. And connection successful! But then:
```
Connection-related Error: Socket closed by Agda
code: 0
signal: null
It's probably because Agda's not happy about the arguments you fed her
```
I would appreciate some help.

`agda -V` runs fine on my bash terminal, I'm on Ubuntu 19.

**Comment by banacorn** [comment]
Oops my bad!
I've changed how agda-mode on Atom works, but didn't gave much thought about this docker thing.

**Comment by banacorn** [comment]
I've update both [README.md](https://github.com/banacorn/docker-agda/blob/master/README.md) and patched agda-mode on Atom. Please give it a try
